"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PyGenTek']
DATA_FILES = ['dna.icns']
OPTIONS = {'argv_emulation': True,
'iconfile': 'dna.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
